language: android


android:
 components:
  - platform-tools
  - tools
#- build-tools-25.0.2
#- android-25




before_script: chmod +x AWSCognitoSampleApp/MySampleApp/gradlew  


script: ./AWSCognitoSampleApp/MySampleApp/gradlew build AWSCognitoSampleApp/MySampleApp #connectedCheck
