language: android
jdk: oraclejdk8


android:
 components:
  - platform-tools
  - tools
#- build-tools-25.0.2
#- android-25

 licenses:
  - 'android-sdk-license-.+' 




before_script: chmod +x AWSCognitoSampleApp/MySampleApp/gradlew  


script: ./AWSCognitoSampleApp/MySampleApp/gradlew -p AWSCognitoSampleApp/MySampleApp connectedCheck
