language: android
jdk: oraclejdk8


android:
 components:
  - platform-tools
  - tools
  - tools
  - build-tools-24.0.2
  - android-23
  - extra-android-m2repository
  - extra-google-m2repository

# licenses:
#  - 'android-sdk-license-.+' 




before_script: 
  - chmod +x AWSCognitoSampleApp/MySampleApp/gradlew  



script: ./AWSCognitoSampleApp/MySampleApp/gradlew -p AWSCognitoSampleApp/MySampleApp connectedCheck
