language: android
jdk: oraclejdk8
sudo: required 

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

android:
 update_sdk: true
 components:
  - platform-tools
  - tools
  - tools
#build tools version
  - build-tools-24.0.2

#compiled sdk version
  - android-25

  - extra-android-m2repository
  - extra-google-m2repository
    




before_script: 
  - chmod +x AWSCognitoSampleApp/MySampleApp/gradlew  



script: ./AWSCognitoSampleApp/MySampleApp/gradlew -p AWSCognitoSampleApp/MySampleApp connectedCheck
