language: android
jdk: oraclejdk8


android:
 components:
  - platform-tools
  - tools
  - tools
#build tools version
  - build-tools-24.0.2

#compiled sdk version
  - android-25

  - extra-android-m2repository
  - extra-google-m2repository





before_script: 
  - chmod +x AWSCognitoSampleApp/MySampleApp/gradlew  



script: ./AWSCognitoSampleApp/MySampleApp/gradlew -p AWSCognitoSampleApp/MySampleApp connectedCheck
