//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub ed578752-3e90-40cf-ad33-0a1eb24f9bf1 aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:5151eb5b-e3b0-4188-b21b-75c6c42a0b97";
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "soengroup-userfiles-mobilehub-1153046571";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-east-1");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_JZd3whM0F";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "53tdqsjsnbujhi2qbm8pr6e0ap";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "17mjcdk4etatj1mld98uo3m1j39uguc3ec5vpurju0e8957hqut3";
}
